import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full flex flex-col bg-gradient-to-b from-[#2F5663] to-[#1a2a33]`}
        style={{ minHeight: "100vh" }}
      >
        <Header />
        <main className="flex-1 w-full flex flex-col items-center justify-center px-2 sm:px-4 md:px-0 pt-20 pb-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}